/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2018-01-29 10:27:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updata_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
            + path + "/";

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <script type=\"text/javascript\" src=\"/jquery/jquery.js\"></script>\n");
      out.write("    <title>更改送货单</title>\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\n");
      out.write("    <meta http-equiv=\"pragma\" content=\"no-cache\">\n");
      out.write("    <meta http-equiv=\"cache-control\" content=\"no-cache\">\n");
      out.write("    <meta http-equiv=\"expires\" content=\"0\">\n");
      out.write("    <meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\n");
      out.write("    <meta http-equiv=\"description\" content=\"This is my page\">\n");
      out.write("    ");

        java.text.SimpleDateFormat simpleDateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        java.util.Date currentTime = new java.util.Date();
        String createtime = simpleDateFormat.format(currentTime).toString();
    
      out.write("\n");
      out.write("    <style type=\"text/css\">\n");
      out.write("        .qiangdu {\n");
      out.write("            width: 100px;\n");
      out.write("            height: 30px;\n");
      out.write("            line-height: 25px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input {\n");
      out.write("            width: 110px;\n");
      out.write("            height: 25px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .g3 {\n");
      out.write("            width: 400px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .xcttd {\n");
      out.write("            width: 200px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "loginOutDiv.jsp", out, true);
      out.write(" \n");
      out.write("<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/updateChuHuoDanById.do\" method=\"post\">\n");
      out.write("    <table border=\"1\" width=\"100%\" height=\"400\" align=\"center\">\n");
      out.write("        <tr>\n");
      out.write("            <th colspan=\"8\" align=\"center\" height=\"100\">淇县信誉商砼有限公司送货单</th>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"100\">编号</td>\n");
      out.write("            <td width=\"200\" colspan=\"3\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("            <input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\n");
      out.write("            </td>\n");
      out.write("            <td width=\"100\" align=\"center\">时间:</td>\n");
      out.write("            <td width=\"300\" ><input name=\"createtime\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.createtime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"100\">计量单位</td>\n");
      out.write("            <td width=\"100\" ><input name=\"jiliangdanwei\" type=\"hidden\" value=\"Kg\">Kg</td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"100\">收货单位</td>\n");
      out.write("            <td colspan=\"3\" width=\"300\"><input  name=\"shouhuodanwei\" class=\"g3\"\n");
      out.write("                                                type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.shouhuodanwei}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"120\" class=\"xcttd\">等级强度</td>\n");
      out.write("            <td width=\"100\" width=\"100\"><select id=\"selectId\" name=\"dengjiqiangdu\"\n");
      out.write("                                                class=\"qiangdu\">\n");
      out.write("                <option value=\"c10\">c10</option>\n");
      out.write("                <option value=\"c15\">c15</option>\n");
      out.write("                <option value=\"c20\">c20</option>\n");
      out.write("                <option value=\"c25\">c25</option>\n");
      out.write("                <option value=\"c30\">c30</option>\n");
      out.write("                <option value=\"c35\">c35</option>\n");
      out.write("            </select></td>\n");
      out.write("            <td width=\"100\">浇筑方式</td>\n");
      out.write("            <td width=\"100\"><input  name=\"jiaozhufangshi\" type=\"text\"\n");
      out.write("                                    value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.jiaozhufangshi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("        </tr>\n");
      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"100\">工程名称</td>\n");
      out.write("            <td colspan=\"3\" width=\"300\"><input  name=\"gongchengname\" class=\"g3\"\n");
      out.write("                                                type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.gongchengname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"120\" class=\"xcttd\">坍塌度</td>\n");
      out.write("            <td width=\"100\" ><input name=\"tantadu\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.tantadu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"100\">抗渗等级</td>\n");
      out.write("            <td width=\"100\" ><input name=\"kangshendengji\" type=\"text\"\n");
      out.write("                                    value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.kangshendengji}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"100\">施工部位</td>\n");
      out.write("            <td colspan=\"3\" width=\"300\"><input  name=\"shigongbuwei\" id=\"g3\"\n");
      out.write("                                                type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.shigongbuwei}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"120\" class=\"xcttd\">现场坍塌度</td>\n");
      out.write("            <td width=\"100\" ><input name=\"xianchangtantadu\" type=\"text\"\n");
      out.write("                                    value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.xianchangtantadu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"100\">到达时间</td>\n");
      out.write("            <td width=\"100\"><input  name=\"daodatime\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.daodatime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"100\">车号</td>\n");
      out.write("            <td width=\"120\" ><input name=\"chehao\" type=\"text\"\n");
      out.write("                                    value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.chehao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"50\">司机</td>\n");
      out.write("            <td width=\"150\"><input  name=\"siji\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.siji}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"100\" class=\"xcttd\">车次</td>\n");
      out.write("            <td width=\"100\" ><input name=\"checi\" type=\"number\" min=\"1\"\n");
      out.write("                                    value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.checi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"100\">本次方量</td>\n");
      out.write("            <td width=\"100\" ><input name=\"bencifangliang\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.bencifangliang}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"100\">毛重</td>\n");
      out.write("            <td width=\"120\" ><input name=\"maozhong\" id=\"maozid\"\n");
      out.write("                                    type=\"number\" step=\"0.01\" min=\"1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.maozhong}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"50\">皮重</td>\n");
      out.write("            <td width=\"150\"><input  name=\"pizhong\"  id=\"pizid\"\n");
      out.write("                                    type=\"number\" step=\"0.01\" min=\"1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.pizhong}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"100\" class=\"xcttd\">净重</td>\n");
      out.write("            <td width=\"100\" step=\"0.01\" min=\"1\"><input  name=\"jingzhong\"  type=\"number\" id=\"jingzid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.jingzhong}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("            <td width=\"100\">累计方量</td>\n");
      out.write("            <td width=\"100\" > <input name=\"leiji\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.leiji}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"100\"  >备注</td>\n");
      out.write("            <td colspan=\"7\" >\n");
      out.write("                <textarea rows=\"10px\" cols=\"20px\" name=\"beizhu\">\n");
      out.write("                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.beizhu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("                </textarea>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("    </table>\n");
      out.write("    <div style=\"float: right\">\n");
      out.write("        <input type=\"button\" value=\"展示所有出货单\" onclick=\"location.href ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/findAll.do'\">\n");
      out.write("        <input type=\"reset\" value=\"清空输入\">\n");
      out.write("        <input type=\"submit\" value=\"更新\">\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    $(document).ready(function(){\n");
      out.write("        $(\"#pizid\").change(function () {\n");
      out.write("            $(\"#jingzid\").val($(\"#maozid\").val()-$(\"#pizid\").val());\n");
      out.write("        });\n");
      out.write("        $(\"#selectId option\").each(function(){ //遍历全部option\n");
      out.write("            var text = $(this).text(); //获取option的text\n");
      out.write("//            var value = $(this).val(); //获取option的value\n");
      out.write("            if(text==\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dan.dengjiqiangdu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\") {\n");
      out.write("                $('#selectId').attr('value',text);\n");
      out.write("            }\n");
      out.write("    })\n");
      out.write("    })\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
